# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_SaveCitraAsli = QtWidgets.QPushButton(self.centralwidget)
        self.button_SaveCitraAsli.setGeometry(QtCore.QRect(20, 480, 93, 28))
        self.button_SaveCitraAsli.setObjectName("button_SaveCitraAsli")
        self.citra_Asli = QtWidgets.QLabel(self.centralwidget)
        self.citra_Asli.setGeometry(QtCore.QRect(20, 30, 531, 441))
        self.citra_Asli.setFrameShape(QtWidgets.QFrame.Box)
        self.citra_Asli.setText("")
        self.citra_Asli.setObjectName("citra_Asli")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 51, 16))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setBaseSize(QtCore.QSize(0, 0))
        self.label_2.setObjectName("label_2")
        self.citra_hasil = QtWidgets.QLabel(self.centralwidget)
        self.citra_hasil.setGeometry(QtCore.QRect(570, 30, 531, 441))
        self.citra_hasil.setFrameShape(QtWidgets.QFrame.Box)
        self.citra_hasil.setText("")
        self.citra_hasil.setObjectName("citra_hasil")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 10, 71, 16))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setBaseSize(QtCore.QSize(0, 0))
        self.label_3.setObjectName("label_3")
        self.button_SaveCitraHasil = QtWidgets.QPushButton(self.centralwidget)
        self.button_SaveCitraHasil.setGeometry(QtCore.QRect(570, 480, 93, 28))
        self.button_SaveCitraHasil.setObjectName("button_SaveCitraHasil")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_SaveCitraAsli.setText(_translate("MainWindow", "Load Citra"))
        self.label_2.setText(_translate("MainWindow", "Citra Asli"))
        self.label_3.setText(_translate("MainWindow", "Citra Hasil"))
        self.button_SaveCitraHasil.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
